12/02/2019
Topic: Exception Continue
           Finally block
           multi-catch blocks
Agenda:
    Morning: Java
    Afternoon: Selenium
package name: day58_Exception
WarmUp:
    1. Write a method called "wait" that causes the current executing thread to sleep for the specific number of seconds
            parameters: double seconds
            return-type: String
            Thread.sleep();
        Note: Exceptions MUST be handled within the methods
    2. write a method called "getData" that can retrieve the data from properties files
            parameters: String Key, String FilePath
            return-type: String
        Note: Exceptions MUST be handled within the methods
Assessment Quiz 15 is due by 1:30 pm
Exception: unwanted or unexpected events
    checked exception(unwanted): occurs during compile time
                                MUST be handled IMMeDIATELY
    unchecked exception(unexpected): occurs during run time
                all the runtimeexceptions are unchecked exception
                EX:
                    NoSuchElemntException
                    WebDriverException
                    TimeoutException
                    ....
create file:
    Mac:
        touch fileName.fileType
    Windows:
        new-item fileName.fileType
properties file: key = value
Properties class: helps us to retrieve data from properties file
                    load(file) ;
FileInputStreamClass: hleps us to read specifc file
Exception Handling:
    1. try  & catch: used for handling exceptions
                    try{
                        Exception code;
                    }catch(ExceptionClass name){
                        code;
                    }
        try block: gets executed if the exception is checked
        catch block: gets executed if the exception is unchecked
        finally block: can use finally block along with try&catch blocks.
                codes in finally ALWAYS gets executed regradless of the exception
                MUST be delared with try&catch block
                    try{
                        Exception code;
                    }catch(ExceptionClass name){
                        code;
                    }finally{
                        code;
                    }
